// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinheriaAgnelloCRUD.Data;

#nullable disable

namespace VinheriaAgnelloCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615152515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("VinheriaAgnelloCRUD.Data.Models.Wine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Winery")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("wines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("79b4e22b-97c8-4e2a-9a26-c8d2a6e87211"),
                            Country = "Brasil",
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Agnello Reserva Tinto",
                            Price = 89.90m,
                            Quantity = 24,
                            Type = "Tinto",
                            Winery = "Vinheria Agnello",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("e79d36a7-ea01-48a0-9c6d-a216d343b9ef"),
                            Country = "Chile",
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Agnello Branco Seco",
                            Price = 74.50m,
                            Quantity = 18,
                            Type = "Branco",
                            Winery = "Vinheria Agnello",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("a1817271-51c8-4f62-8446-c41da16a9f0a"),
                            Country = "Argentina",
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Agnello Rose",
                            Price = 69.90m,
                            Quantity = 12,
                            Type = "Rose",
                            Winery = "Vinheria Agnello",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
